apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  destination:
    name: ''
    namespace: harbor
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.goharbor.io'
    targetRevision: 1.11.0
    chart: harbor
    helm:
      parameters:
        - name: expose.tls.enabled
          value: 'false'
        - name: expose.type
          value: nodePort
        - name: externalURL
          value: 'http://localhost:30002'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
