apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: consul
  project: default
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: consul
    targetRevision: 1.14.4
    helm:
      valueFiles: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true