apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  destination:
    name: ''
    namespace: harbor
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.goharbor.io'
    targetRevision: 1.11.0
    chart: harbor
    helm:
      parameters:
        - name: expose.tls.enabled
          value: 'true'
        - name: expose.type
          value: ingress
        - name: expose.tls.certSource
          value: secret
        - name: expose.tls.secret.secretName
          value: 'quickstart-example-tls'
        - name: externalURL
          value: 'consul.digitor.dk'
  sources: []
  project: default
  syncPolicy: null
 #   automated:
 #     prune: false
 #     selfHeal: false
