apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  destination:
    name: ''
    namespace: loki
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://grafana.github.io/helm-charts'
    targetRevision: 6.52.0
    chart: grafana
    helm:
      parameters:
        - name: sidecar.datasources.label
          value: ''
        - name: sidecar.datasources.enabled
          value: 'true'
        - name: 'sidecar.datasources.maxLines'
          value: '1000'
        - name: 'loki.enabled'
          value: 'true'
        - name: 'loki.isDefault'
          value: 'true'
        - name: 'grafana.enabled'
          value: 'true'
        - name: 'prometheus.enabled'
          value: 'true'
        - name: 'prometheus.isDefault'
          value: 'false'
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
