apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  project: default
  source:
    path: harbor/
    repoURL: https://github.com/RasmusLynge/argoCD.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
