apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: charts/argo-cd
    repoURL: https://github.com/RasmusLynge/argoCD.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
