apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-30 - 20:16:12 +0000
  labels:
    app.kubernetes.io/name: sagdokindeks-message-sender
    app.kubernetes.io/version: 1.0.0
  name: sagdokindeks-message-sender
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: sagdokindeks-message-sender
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-30 - 20:16:12 +0000
  labels:
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/name: sagdokindeks-message-sender
  name: sagdokindeks-message-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: sagdokindeks-message-sender
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-30 - 20:16:12 +0000
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: sagdokindeks-message-sender
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/dafolo-digital/sagdokindeks-message-sender:1.0.0
        imagePullPolicy: Always
        name: sagdokindeks-message-sender
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
