apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  project: default
  source:
    repoURL: https://helm.goharbor.io
    chart: harbor
    targetRevision: 1.11.0
    helm:
      valueFiles: []
  syncPolicy:
    automated:
      prune: true
      selfHeal: true