apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-30 - 11:45:42 +0000
  labels:
    app.kubernetes.io/name: core-message-entry
    app.kubernetes.io/version: 1.0.0
  name: core-message-entry
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: core-message-entry
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-30 - 11:45:42 +0000
      labels:
        app.kubernetes.io/name: core-message-entry
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/dafolo-digital/core-message-entry:1.0.0
        imagePullPolicy: Always
        name: core-message-entry
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-30 - 11:45:42 +0000
  labels:
    app.kubernetes.io/name: core-message-entry
    app.kubernetes.io/version: 1.0.0
  name: core-message-entry
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: core-message-entry
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-30 - 11:45:42 +0000
  labels:
    app.kubernetes.io/name: core-message-entry
    app.kubernetes.io/version: 1.0.0
  name: core-message-entry
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: core-message-entry
            port:
              name: http
        path: /
        pathType: Prefix
