argo-cd:
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

# helm install argo-cd charts/argo-cd/ --create-namespace --namespace argocd
# kubectl port-forward svc/argo-cd-argocd-server -n argocd 8080:443

# kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d