apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
spec:
  destination:
    name: ''
    namespace: consul
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://helm.releases.hashicorp.com'
    targetRevision: 1.1.0
    chart: consul
    helm:
      parameters:
#        - name: global.tls.enabled
#          value: 'true'
        - name: global.acls.manageSystemACLs
          value: 'true'
        - name: server.enabled
          value: 'true'
        - name: ui.enabled
          value: 'true'
        - name: connectInject.enabled
          value: 'false'
#        - name: syncCatalog.enabled   <-- Hvad er det til? 
#          value: 'true'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
