apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-30 - 11:30:16 +0000
  labels:
    app.kubernetes.io/name: sagdokindeks-api-producer
    app.kubernetes.io/version: 1.0.2
  name: sagdokindeks-api-producer
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: sagdokindeks-api-producer
    app.kubernetes.io/version: 1.0.2
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-30 - 11:30:16 +0000
  labels:
    app.kubernetes.io/name: sagdokindeks-api-producer
    app.kubernetes.io/version: 1.0.2
  name: sagdokindeks-api-producer
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: sagdokindeks-api-producer
      app.kubernetes.io/version: 1.0.2
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-30 - 11:30:16 +0000
      labels:
        app.kubernetes.io/name: sagdokindeks-api-producer
        app.kubernetes.io/version: 1.0.2
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/dafolo-digital/sagdokindeks-api-producer:1.0.2
        imagePullPolicy: Always
        name: sagdokindeks-api-producer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
