apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-28 - 10:27:37 +0000
  labels:
    app.kubernetes.io/name: sagdokindeks-api-producer
    app.kubernetes.io/version: 1.0.1
  name: sagdokindeks-api-producer
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: sagdokindeks-api-producer
    app.kubernetes.io/version: 1.0.1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-28 - 10:27:37 +0000
  labels:
    app.kubernetes.io/version: 1.0.1
    app.kubernetes.io/name: sagdokindeks-api-producer
  name: sagdokindeks-api-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.1
      app.kubernetes.io/name: sagdokindeks-api-producer
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-28 - 10:27:37 +0000
      labels:
        app.kubernetes.io/version: 1.0.1
        app.kubernetes.io/name: sagdokindeks-api-producer
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: ghcr.io/dafolo-digital/sagdokindeks-api-producer:1.0.1
        imagePullPolicy: Always
        name: sagdokindeks-api-producer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      imagePullSecrets:
      - name: regcred
