---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: test-rasmus
  name: test-rasmus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/name: test-rasmus
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/name: test-rasmus
    spec:
      containers:
      - name: test-rasmus
        image: ghcr.io/dafolo-digital/test-rasmus:1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            name: http
      imagePullSecrets:
        - name: regcred
          type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-01 - 10:08:03 +0000
  labels:
    app.kubernetes.io/name: argo-test
    app.kubernetes.io/version: 1.0.0
  name: argo-test
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: argo-test
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
