apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quarkus-pipeline-test-ingress
  namespace: dafolo
   annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - digitor.com
    secretName: quickstart-example-tls
  rules:
    - host: digitor.dk
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: quarkus-pipeline-test
              port:
                number: 80
