apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-08 - 09:46:33 +0000
  labels:
    app.kubernetes.io/version: 0.0.2
    app.kubernetes.io/name: quarkus-pipeline-test
  name: quarkus-pipeline-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.2
      app.kubernetes.io/name: quarkus-pipeline-test
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-08 - 09:46:33 +0000
      labels:
        app.kubernetes.io/version: 0.0.2
        app.kubernetes.io/name: quarkus-pipeline-test
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: jenkins/quarkus-pipeline-test:0.0.2
        imagePullPolicy: Always
        name: quarkus-pipeline-test
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-08 - 09:46:33 +0000
  labels:
    app.kubernetes.io/name: quarkus-pipeline-test
    app.kubernetes.io/version: 0.0.2
  name: quarkus-pipeline-test
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: quarkus-pipeline-test
    app.kubernetes.io/version: 0.0.2
  type: ClusterIP
